language: java
sudo: required
dist: trusty

before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 5E6DA83306132997
  - sudo apt-add-repository "deb http://zeroc.com/download/apt/ubuntu14.04 stable main"
  - sudo apt-get update -q
  - sudo apt-get install libzeroc-ice-java -y

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
  - DIR=$PWD; (cd /tmp; gradle wrapper --gradle-version=5.2.1; mv .gradle gradle gradlew $DIR)

script:
  - ./gradlew publishToMavenLocal

notifications:
  slack:
    secure: IQdjoLlyS+p0NLlguni6V594nG7Yr6RI0YHJ/d19ITZ/6sGTtSxgUL1ekT8O0eBqjg7MtyPX35xioHA3QkklX5Sqh7dBCByChjegQApxTjsSRp7oB/mzaVGNbmWRXNOUEi/8INP+HAaBoHv722WHTbaYNm4ZEnhtWA0v6HpW5Fs=
